close all
clear rcdisplay

rcdisplay = RCDisplay(RC, 2, 2, ...
    @(RC, ~, data) displayDataLog(RC, 0, data, 1, 2), ...
    @(RC, ~, data) displayDataLog(RC, 0, data, 3, 4), ...
    @displayKeyboardControl, ...
    @displayRCState);

rcdisplay.open();